services:
  tests:
    build:
      context: .
      dockerfile: testsDockerfile
    stdin_open: true
    tty: true
  server:
    volumes:
      - ./data:/usr/src/mytest/data
    build:
      context: .
      dockerfile: Dockerfile.server
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    stdin_open: true
    tty: true
    depends_on:
      - server