services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    stdin_open: true
    tty: true
  
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/usr/src/myserver/data
    container_name: netflix-project
    working_dir: /usr/src/myserver/build
  
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    tty: true
    stdin_open: true
    init: true
    container_name: netflix-project
    working_dir: /usr/src/myclient